import type { FormConfig } from '../types'
import { generateId } from './index'

export interface FormTemplate {
  id: string
  icon: string
  name: string
  description: string
  fieldCount: number
  build(): FormConfig
}

function baseConfig(title: string, description: string): Omit<FormConfig, 'fields'> {
  return {
    title,
    description,
    customMessage: '',
    webhookUrl: '',
    webhookUsername: 'Форма обратной связи',
    webhookAvatarUrl: 'https://pngimg.com/uploads/discord/discord_PNG3.png',
    organization: 'LSPD',
    sendAsPlainText: false,
    displayUsername: true,
    showAdvancedSettings: false,
    sendQuestionNumbers: true,
    sendEmojis: false,
    sendColons: true,
    conditionalMessages: [],
  }
}

export const formTemplates: FormTemplate[] = [
  {
    id: 'anketa',
    icon: '📋',
    name: 'Анкета',
    description: 'Стандартная анкета для вступления',
    fieldCount: 6,
    build(): FormConfig {
      return {
        ...baseConfig('Анкета на вступление', 'Заполните анкету полностью'),
        fields: [
          {
            id: generateId(),
            type: 'text',
            label: 'Имя персонажа',
            placeholder: '',
            required: true,
            icon: 'user',
            options: [],
            formula: '',
            showTextInResponse: true,
            defaultValue: '',
            maxFiles: 10,
            conditional: null,
            customWebhook: null,
          },
          {
            id: generateId(),
            type: 'text',
            label: 'Discord ID',
            placeholder: '',
            required: true,
            icon: 'question',
            options: [],
            formula: '',
            showTextInResponse: true,
            defaultValue: '',
            maxFiles: 10,
            conditional: null,
            customWebhook: null,
          },
          {
            id: generateId(),
            type: 'text',
            label: 'Возраст персонажа',
            placeholder: '',
            required: true,
            icon: 'question',
            options: [],
            formula: '',
            showTextInResponse: true,
            defaultValue: '',
            maxFiles: 10,
            conditional: null,
            customWebhook: null,
          },
          {
            id: generateId(),
            type: 'textarea',
            label: 'Биография',
            placeholder: 'Расскажите о персонаже...',
            required: true,
            icon: 'comment',
            options: [],
            formula: '',
            showTextInResponse: true,
            defaultValue: '',
            maxFiles: 10,
            conditional: null,
            customWebhook: null,
          },
          {
            id: generateId(),
            type: 'textarea',
            label: 'Предыдущий опыт RP',
            placeholder: '',
            required: false,
            icon: 'comment',
            options: [],
            formula: '',
            showTextInResponse: true,
            defaultValue: '',
            maxFiles: 10,
            conditional: null,
            customWebhook: null,
          },
          {
            id: generateId(),
            type: 'textarea',
            label: 'Почему хотите вступить?',
            placeholder: '',
            required: true,
            icon: 'comment',
            options: [],
            formula: '',
            showTextInResponse: true,
            defaultValue: '',
            maxFiles: 10,
            conditional: null,
            customWebhook: null,
          },
        ],
      }
    },
  },
  {
    id: 'raport',
    icon: '🚔',
    name: 'Рапорт',
    description: 'Рапорт о происшествии',
    fieldCount: 5,
    build(): FormConfig {
      return {
        ...baseConfig('Рапорт о происшествии', ''),
        fields: [
          {
            id: generateId(),
            type: 'text',
            label: 'ФИО офицера',
            placeholder: '',
            required: true,
            icon: 'user',
            options: [],
            formula: '',
            showTextInResponse: true,
            defaultValue: '',
            maxFiles: 10,
            conditional: null,
            customWebhook: null,
          },
          {
            id: generateId(),
            type: 'text',
            label: 'Должность',
            placeholder: '',
            required: true,
            icon: 'question',
            options: [],
            formula: '',
            showTextInResponse: true,
            defaultValue: '',
            maxFiles: 10,
            conditional: null,
            customWebhook: null,
          },
          {
            id: generateId(),
            type: 'text',
            label: 'Дата происшествия',
            placeholder: 'ДД.ММ.ГГГГ',
            required: true,
            icon: 'question',
            options: [],
            formula: '',
            showTextInResponse: true,
            defaultValue: '',
            maxFiles: 10,
            conditional: null,
            customWebhook: null,
          },
          {
            id: generateId(),
            type: 'textarea',
            label: 'Описание',
            placeholder: 'Опишите подробно...',
            required: true,
            icon: 'comment',
            options: [],
            formula: '',
            showTextInResponse: true,
            defaultValue: '',
            maxFiles: 10,
            conditional: null,
            customWebhook: null,
          },
          {
            id: generateId(),
            type: 'textarea',
            label: 'Принятые меры',
            placeholder: '',
            required: true,
            icon: 'comment',
            options: [],
            formula: '',
            showTextInResponse: true,
            defaultValue: '',
            maxFiles: 10,
            conditional: null,
            customWebhook: null,
          },
        ],
      }
    },
  },
  {
    id: 'zayavka',
    icon: '💼',
    name: 'Заявка',
    description: 'Заявка на повышение или перевод',
    fieldCount: 5,
    build(): FormConfig {
      return {
        ...baseConfig('Заявка', ''),
        fields: [
          {
            id: generateId(),
            type: 'text',
            label: 'ФИО',
            placeholder: '',
            required: true,
            icon: 'user',
            options: [],
            formula: '',
            showTextInResponse: true,
            defaultValue: '',
            maxFiles: 10,
            conditional: null,
            customWebhook: null,
          },
          {
            id: generateId(),
            type: 'text',
            label: 'Текущая должность',
            placeholder: '',
            required: true,
            icon: 'question',
            options: [],
            formula: '',
            showTextInResponse: true,
            defaultValue: '',
            maxFiles: 10,
            conditional: null,
            customWebhook: null,
          },
          {
            id: generateId(),
            type: 'text',
            label: 'Желаемая должность',
            placeholder: '',
            required: true,
            icon: 'question',
            options: [],
            formula: '',
            showTextInResponse: true,
            defaultValue: '',
            maxFiles: 10,
            conditional: null,
            customWebhook: null,
          },
          {
            id: generateId(),
            type: 'textarea',
            label: 'Причина',
            placeholder: '',
            required: true,
            icon: 'comment',
            options: [],
            formula: '',
            showTextInResponse: true,
            defaultValue: '',
            maxFiles: 10,
            conditional: null,
            customWebhook: null,
          },
          {
            id: generateId(),
            type: 'textarea',
            label: 'Доп. сведения',
            placeholder: '',
            required: false,
            icon: 'comment',
            options: [],
            formula: '',
            showTextInResponse: true,
            defaultValue: '',
            maxFiles: 10,
            conditional: null,
            customWebhook: null,
          },
        ],
      }
    },
  },
  {
    id: 'zhaloba',
    icon: '🆘',
    name: 'Жалоба',
    description: 'Жалоба на нарушение правил',
    fieldCount: 5,
    build(): FormConfig {
      return {
        ...baseConfig('Жалоба', ''),
        fields: [
          {
            id: generateId(),
            type: 'text',
            label: 'Ваш ник в игре',
            placeholder: '',
            required: true,
            icon: 'user',
            options: [],
            formula: '',
            showTextInResponse: true,
            defaultValue: '',
            maxFiles: 10,
            conditional: null,
            customWebhook: null,
          },
          {
            id: generateId(),
            type: 'text',
            label: 'На кого жалоба',
            placeholder: '',
            required: true,
            icon: 'question',
            options: [],
            formula: '',
            showTextInResponse: true,
            defaultValue: '',
            maxFiles: 10,
            conditional: null,
            customWebhook: null,
          },
          {
            id: generateId(),
            type: 'text',
            label: 'Когда произошло',
            placeholder: 'ДД.ММ.ГГГГ ЧЧ:ММ',
            required: true,
            icon: 'question',
            options: [],
            formula: '',
            showTextInResponse: true,
            defaultValue: '',
            maxFiles: 10,
            conditional: null,
            customWebhook: null,
          },
          {
            id: generateId(),
            type: 'textarea',
            label: 'Что произошло',
            placeholder: 'Опишите ситуацию подробно',
            required: true,
            icon: 'comment',
            options: [],
            formula: '',
            showTextInResponse: true,
            defaultValue: '',
            maxFiles: 10,
            conditional: null,
            customWebhook: null,
          },
          {
            id: generateId(),
            type: 'text',
            label: 'Доказательства',
            placeholder: 'Ссылка на видео/скриншот',
            required: false,
            icon: 'question',
            options: [],
            formula: '',
            showTextInResponse: true,
            defaultValue: '',
            maxFiles: 10,
            conditional: null,
            customWebhook: null,
          },
        ],
      }
    },
  },
]
